import os
import base64

from mistralai import Mistral
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file
import logging  
logging.basicConfig(level=logging.INFO)
api_key = os.environ["MISTRAL_API_KEY"]
model = "magistral-small-2509"

from pydantic import BaseModel, Field, field_validator
client = Mistral(api_key=api_key)


class ICAAnalysis(BaseModel):
    ica_channels_to_remove: list = Field(
        description="List of ICA channels to remove based on the analysis"
    )
    justification: str = Field(
        description="A brief explanation of the reasoning behind the selected ICA channels, referencing specific features in the ICA plots such as artifacts, noise, or other relevant observations."
    )
messages = [{
  "role": "system",
  "content": [
    {
      "type": "text",
      "text": "# HOW YOU SHOULD THINK AND ANSWER\n\nFirst draft your thinking process (inner monologue) until you arrive at a response. Format your response using Markdown, and use LaTeX for any mathematical equations. Write both your thoughts and the response in the same language as the input.\n\nYour thinking process must follow the template below:"
    },
    {
      "type": "thinking",
      "thinking": [
        {
          "type": "text",
          "text": "Your thoughts or/and draft, like working through an exercise on scratch paper. Be as casual and as long as you want until you are confident to generate the response to the user."
        }
      ]
    },
    {
      "type": "text",
      "text": "Here, provide a self-contained response."
    }
  ]
}]
messages += [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": """You are a helpful assistant for EEG data analysis. I will give you an image of ICA plots. I want you to analyze the plot and identify which ICA channels should be removed. To answer, here are some rules to identify bad ICA components:
                - Vertical eye movement components will contain blinks in the data
                - Horizontal eye movement components will look like step functions
                - The pattern generated by the heart is very typical and is known as a QRS complex (it looks like a sharp peak followed by a smaller inverted peak)
                - Muscle artifacts typically have a high-frequency pattern and are often localized to specific channels, especially those near the face and neck. They can appear as bursts of high-frequency activity in the ICA components
                - Strong peak in power spectrum at either 50Hz or 60Hz
                - If an ICA component looks like the EOG signal (which is at the bottom of the plot) it is likely an eye movement artifact and should be removed.
                Respond by providing a list of ICA channels to remove based on the analysis and the rules. I want only to identify the channels associated to these rules.
                Also do a brief justification for your answer."""
            },
            {
                "type": "image_url",
                "image_url": "https://image2url.com/r2/default/images/1772313433048-17b9d55d-3dce-4fb7-a7bd-1e3e5586ca47.png"
            }
        ]
    }
]

chat_response = client.chat.parse(
    model=model,
    messages=messages,
    prompt_mode="reasoning",
    response_format=ICAAnalysis,
    temperature=0.1,
)
logging.info(f"Model response: {chat_response.choices[0].message.content}")

